[project]
name = "whotovisit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bibtexparser>=1.4.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
]
